AWSTemplateFormatVersion: 2010-09-09
Description: 
        Kafayat Itunu- final project
Resources:
    MainVPC:
        Type: 'AWS::EC2::VPC'
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: 'true'
